import React from 'react'
import Helmet from 'react-helmet'
import { Link } from 'gatsby'
import { Global, css } from '@emotion/core'
import styled from 'styled-components'
import variables from '../variables'
import bases from '../bases'
import favicon from '../images/favicon.png'

class Template extends React.Component {
  render() {
    return (
      <main>
        <Helmet>
          <meta name="theme-color" content={variables.colorMain} />
          <link href="https://fonts.googleapis.com/css?family=Montserrat:500,600" rel="stylesheet" />
          <link rel="shortcut icon" href={favicon} />
        </Helmet>
        <Global styles={bases} />
        {children}
        <Footer>
          <div>Designed By <a href='https://yet.unresolved.xyz'>Daisuke Tsuji</a></div>
          <div>Generated By <a href='https://www.gatsbyjs.org/' rel='nofollow'>GatsbyJS</a></div>
          <div>Hosting On <a href='https://www.netlify.com/' rel='nofollow'>Netlify</a></div>
        </Footer>
      </main>
    )
  }
}

export default Template
