import React from 'react'
import Helmet from 'react-helmet'
import styled from 'styled-components'
import variables from '../styles/variables'
import bases from '../styles/bases'

const Footer = styled.footer`
  padding: 1.5rem 1rem;
  font-size: .8rem;
  line-height: 1.5rem;
  text-align: center;

  a {
    color: ${variables.colorAccent};
  }
`

class Template extends React.Component {
  render() {
    const { _, children } = this.props

    return (
      <main>
        <Helmet>
          <link href="https://fonts.googleapis.com/css?family=Montserrat:500,600" rel="stylesheet" />
        </Helmet>
        <style>{bases}</style>
        {children()}
        <Footer>
          <div>Designed By <a href='https://yet.unresolved.xyz'>Daisuke Tsuji</a></div>
          <div>Generated By <a href='https://www.gatsbyjs.org/' rel='nofollow'>GatsbyJS</a></div>
          <div>Hosted By <a href='https://www.netlify.com/' rel='nofollow'>Netlify</a></div>
        </Footer>
      </main>
    )
  }
}

export default Template
